# Generated by Django 5.1.4 on 2025-06-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Partial', 'Partial'), ('Overdue', 'Overdue')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_term',
            field=models.CharField(choices=[('Term 1', 'Term 1 (Months 1-3)'), ('Term 2', 'Term 2 (Months 4-6)'), ('Term 3', 'Term 3 (Months 7-9)'), ('Term 4', 'Term 4 (Months 10-12)')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
