# Generated by Django 5.1.4 on 2025-06-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_payment_amount_due_payment_due_date_payment_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_term',
            field=models.CharField(choices=[('Term 1', 'Term 1 (June 8 - August 31)'), ('Term 2', 'Term 2 (September 1 - November 30)'), ('Term 3', 'Term 3 (December 1 - February 28)'), ('Term 4', 'Term 4 (March 1 - May 31)')], max_length=10),
        ),
    ]
